import { ArrowRight, ArrowUp, BookOpen, ChevronDown, FileSearch, History, Layers3, LoaderCircle, MessageSquarePlus, Sparkles, Square, Trash2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Link } from 'react-router-dom';
import { useChat } from './hooks/useChat';
import Sources from './components/Sources';
import RetrievalDiagnostics from './components/RetrievalDiagnostics';
import s from './style/index.module.scss';

export default function Chat() {
  const m = useChat();
  const ready = m.documents.filter(d => d.status === 'ready' && !d.needs_reindex);
  const configured = m.settings?.allow_external && m.settings.chat_model && (!m.settings.chat_url.includes('api.deepseek.com') || m.settings.chat_key_set);
  const prompts = ['帮我梳理这些资料的核心观点', '这些资料中提到了哪些重要安排？', '比较资料中不同方案的优缺点'];
  return <>
    <div className="pageHeading"><div><div className="eyebrow">A CONVERSATION WITH YOUR KNOWLEDGE</div><h1>向你的知识，提个问题</h1><p className="subtitle">从你上传的资料出发，让每一个答案都有依据。</p></div><button className="secondary" disabled={m.busy || m.loading} onClick={m.newChat}><MessageSquarePlus size={15} />新对话</button></div>
    {!configured && <div className="notice"><Sparkles size={16} /><span>先连接 DeepSeek，开启有依据的问答。本地向量模型会自动处理你的资料。 <Link className={s.settingsLink} to="/settings">前往模型设置 <ArrowRight size={12} /></Link></span></div>}
    <div className={s.layout}><section className={s.chat}>
      <header className={s.chatHeader}><span><span className={s.botIcon}><Layers3 size={16} /></span><span>知识助手<small>基于你的资料回答</small></span></span><div className={s.history}><History size={14} /><select aria-label="历史会话" disabled={m.busy || m.loading} value={m.conversationId ?? ''} onChange={e => m.loadConversation(e.target.value)}><option value="">历史会话</option>{m.conversations.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select>{m.conversationId && <button className="iconButton" aria-label="删除当前会话" disabled={m.busy || m.loading} onClick={m.deleteConversation}><Trash2 size={13} /></button>}</div></header>
      <div className={s.scope}><BookOpen size={13} /><span>提问范围</span><select aria-label="问答知识库" disabled={m.busy || m.loading} value={m.kb} onChange={e => m.setScope(e.target.value)}>{m.kbs.map(k => <option key={k.id} value={k.id}>{k.name}</option>)}</select><span className={s.scopeSeparator} /><select aria-label="指定文档" disabled={m.busy || m.loading} value={m.selectedDoc} onChange={e => m.setScope(m.kb, e.target.value)}><option value="">全部资料 · {ready.length} 份可用</option>{m.documents.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></div>
      <div className={s.messages} aria-live="polite">
        {m.loading ? <div className="loading"><LoaderCircle className="spin" size={20} />加载会话中</div> : !m.messages.length ? <div className={s.welcome}><div className={s.orbit}><span><Sparkles size={30} strokeWidth={1.2} /></span><i /><b /></div><h2>你好，今天想了解什么？</h2><p>我会在你的资料中寻找线索，<br />把分散的信息，整理成清晰的答案。</p><div className={s.promptList}>{prompts.map((p, i) => <button key={p} disabled={m.busy} onClick={() => m.setInput(p)}>{i === 0 ? <FileSearch size={16} /> : i === 1 ? <BookOpen size={16} /> : <Layers3 size={16} />}<span>{p}</span><ArrowRight size={13} /></button>)}</div></div> : m.messages.map(message => <article className={`${s.message} ${message.role === 'user' ? s.user : s.assistant}`} key={message.id}>{message.role === 'assistant' && <div className={s.answerName}><span><Sparkles size={13} /></span>知屿<span className={s.ai}>AI</span></div>}<div className={s.bubble}>{message.content ? <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{message.content}</ReactMarkdown></div> : <span className={s.thinking}><LoaderCircle className="spin" size={14} />{m.busy ? m.status : '回答未完成'}</span>}{message.status === 'interrupted' && <span className={s.interrupted}>此回答未完成</span>}</div>{message.role === 'assistant' && message.citations.length > 0 && <div className={s.citations}>{message.citations.map(c => <button key={c.id} onClick={() => m.selectSource(c, message.citations)}><span>{c.id}</span>{c.deleted ? '来源已删除' : c.name}</button>)}</div>}{message.role === 'assistant' && message.status === 'complete' && <><RetrievalDiagnostics data={message.retrieval_diagnostics} /><button className="secondary" onClick={() => m.saveNote(message)} disabled={m.saved[message.id]}>{m.saved[message.id] ? '已保存为笔记' : '保存为笔记'}</button></>}</article>)}<div ref={m.bottom} />
      </div>
      <div className={s.composerArea}>{m.error && <div className="notice error" role="alert">{m.error}</div>}{m.warning && <div className="notice" role="status">{m.warning}</div>}<form className={s.composer} onSubmit={e => { e.preventDefault(); m.send(); }}><textarea aria-label="向知识库提问" placeholder="向你的知识库提问…" value={m.input} maxLength={4000} onChange={e => m.setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); m.send(); } }} rows={2} disabled={m.loading} /><div className={s.composerFooter}><span><FileSearch size={12} />仅检索当前范围内的资料</span>{m.busy ? <button type="button" className={s.send} aria-label="停止生成" onClick={m.stop}><Square size={15} fill="currentColor" /></button> : <button type="submit" className={s.send} disabled={!m.input.trim() || m.loading} aria-label="发送问题"><ArrowUp size={19} /></button>}</div></form><p className={s.disclaimer}>Enter 发送 · Shift + Enter 换行<span>AI 回答请结合原文核对</span></p></div>
    </section><Sources sources={m.sources} active={m.activeSource} onSelect={m.selectSource} /></div>
  </>;
}
